### ISSUE TITLE
[?] Authenticate in WP through Symfony

### ISSUE THREAD

**Issue by Molkobain** [ekino/ekino-wordpress-symfony#1]
Hi,

from what I've understand from the documentation, this plugin enable someone that log in to wordpress to be logged in into Symfony as well, right ? I would like to do the opposite : When a user logs in Symfony it would logged him into WP too, so he would be able to comment with his Symfony account. Is it possible with your plugin ?

Thanks

**Comment by nicolaskern** [comment]
Hi,

Has this use case been solved in the meantime?

Best,
Nicolas
